github.com:
    users:
        s166harth:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: s166harth
